# Cloudflare Pages configuration for Pet Heart Animal Clinic
name = 'petheartweb'
compatibility_date = '2025-01-15'

[build]
command = './build.sh'

[assets]
directory = './public'
not_found_handling = '404-page'